ISEIapp/urls.py
from django.contrib import admin  #default admin site built by django
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('teachercert.urls')),
    path('', include('emailing.urls')),
    path('', include('reporting.urls')),
    path('', include('services.urls')),
    path('', include('accreditation.urls')),
    path('', include('apr.urls')),
    path('', include('selfstudy.urls')),
    path('', include('annualvisit.urls')),

    # path('paypal/', include('paypal.standard.ipn.urls')),
    # path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #static files served by the server
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #static files uploaded by the user during development

#if settings.DEBUG:
#    import debug_toolbar

#    urlpatterns += [
#       path('__debug__/', include(debug_toolbar.urls)),
#   ]

apr/urls.py
from django.urls import path
from . import views


urlpatterns = [

    #ISEI APR addition links
    path('manage_apr/<int:accreditation_id>/', views.manage_apr, name='manage_apr'),
    path('apr/<int:apr_id>/add_action_plan_directives/', views.add_action_plan_directives, name='add_action_plan_directives'),
    path('apr/<int:apr_id>/add_priority_directives/', views.add_priority_directives, name='add_priority_directives'),
    path('apr/<int:apr_id>/add_directives/', views.add_directives, name='add_directives'),
    path('apr/<int:apr_id>/add_recommendations/', views.add_recommendations, name='add_recommendations'),

    path('apr/<int:accreditation_id>/action_plan/', views.manage_action_plan, name='add_action_plan'),
    path('apr/<int:accreditation_id>/action_plan/<int:action_plan_id>/', views.manage_action_plan, name='edit_action_plan'),


    path('apr_progress_report/<int:apr_id>/', views.apr_progress_report, name='apr_progress_report'),
    path('update_progress/<int:progress_id>/', views.update_progress, name='update_progress'),
    path('update_progress_status/', views.update_progress_status, name='update_progress_status'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('update_actionplandirective_completed_date/', views.update_actionplandirective_completed_date, name='update_actionplandirective_completed_date'),

    path('apr/<int:apr_id>/update-timestamp/', views.update_apr_timestamp, name='update_apr_timestamp'),
    path('apr/<int:apr_id>/submit-timestamp/', views.submit_apr_timestamp, name='submit_apr_timestamp'),

]

reporting/urls.py
from django.urls import path
from . import views
from .views import StudentExcelDownload, PersonnelListView


urlpatterns = [
    #individual school reporting
    path('student_report/<int:arID>/', views.student_report, name='student_report'),
    path('student_import_dashboard/<int:arID>/', views.student_import_dashboard, name='student_import_dashboard'),
    path('student_excel_download/', StudentExcelDownload.as_view(), name='student_excel_download'),
    path('student_report_display/<int:arID>/', views.student_report_display,
         name='student_report_display'),
    path('import_students_prev_year/<int:arID>/', views.import_students_prev_year, name='import_students_prev_year'),
    path('tn_student_export/<int:arID>/', views.tn_student_export, name='tn_student_export'),

    path('employee_report/<int:arID>/', views.employee_report, name='employee_report'),
    path('employee/report/<int:arID>/all/', views.employee_report, {'show_all': True}, name='employee_report_all'),
    path('employee_add_edit/<int:arID>/<int:personnelID>/', views.employee_add_edit, name='employee_edit'),
    path('employee_add_edit/<int:arID>/<str:positionCode>/', views.employee_add_edit, name='employee_add'),
    path('import_employee_prev_year/<int:arID>/', views.import_employee_prev_year, name='import_employee_prev_year'),

    path('day190_report/<int:arID>/', views.day190_report, name='day190_report'),
    path('inservice_report/<int:arID>/', views.inservice_report, name='inservice_report'),
    path('opening_report/<int:arID>/', views.opening_report, name='opening_report'),
    path('closing_report/<int:arID>/', views.closing_report, name='closing_report'),

    path('ap_report/<int:arID>//', views.ap_report, name='ap_report'),

    path('day190_report_display/<int:arID>/', views.day190_report_display, name='day190_report_display'),
    path('employee_report_display/<int:arID>/', views.employee_report, name='employee_report_display'),
    path('employee_report/<int:arID>/export/', views.export_employee_report, name='employee_report_export'),

    path('inservice_report_display/<int:arID>/', views.inservice_report_display, name='inservice_report_display'),
    path('opening_report_display/<int:arID>/', views.opening_report_display, name='opening_report_display'),
    path('closing_report_display/<int:arID>/', views.closing_report_display, name='closing_report_display'),

    path('worthy_student_scholarship/<int:arID>/', views.worthy_student_scholarship, name='worthy_student_scholarship'),
    path('worthy_student_scholarship_display/<int:arID>/', views.worthy_student_scholarship_display, name='worthy_student_scholarship_display'),
    path('worthy_student_scholarship_non_member/<int:schoolID>/', views.worthy_student_scholarship_non_member, name='worthy_student_scholarship_non_member'),

    path('ap_report_display/<int:arID>//', views.ap_report_display, name='ap_report_display'),


    #directories
    path('school_directory/', views.school_directory, name='school_directory'),
    path('personnel_directory/', PersonnelListView.as_view(), name='personnel_directory'),
    path('personnel_directory/<str:schoolID>/', PersonnelListView.as_view(), name='personnel_directory'),
    path('school_personnel_directory/', views.school_personnel_directory, name='school_personnel_directory'),

    #isei
    path('isei_reporting_dashboard/', views.isei_reporting_dashboard, name='isei_reporting_dashboard'),
    path('isei_worthy_student_scholarship/', views.isei_worthy_student_scholarship, name='isei_worthy_student_scholarship'),


    #Data Analysis

    #Staff Retention
    path('staff_retention_school/<int:schoolID>/', views.staff_retention_school, name='staff_retention_school'),
    path('staff_retention_all/', views.staff_retention_all, name='staff_retention_all'),

    #Student Enrollment
    path('longitudinal_enrollment/', views.longitudinal_enrollment, name='longitudinal_enrollment'),
    path('longitudinal_enrollment/<str:individual_school_name>/', views.longitudinal_enrollment, name='longitudinal_enrollment_single'),

    path('add_enrollment/<str:school_name>/<str:year_name>/', views.add_enrollment, name='add_enrollment_with_school_year'),
    path('add_enrollment/<str:school_name>/', views.add_enrollment, name='add_enrollment_with_school'),
    path('add_enrollment/', views.add_enrollment, name='add_enrollment'),


    #ajax
    path('ajax/get-teacher-email/', views.get_teacher_email, name="get_teacher_email"),

    #Reporting
    path('TN_reports/download/<str:schoolyearID>', views.download_TN_reports, name='download_TN_reports'),
    path('NCPSA_directory/download/<str:schoolyearID>', views.download_NCPSA_directory, name='download_NCPSA_directory'),

]

reporting/models.py
from django.db import models
#from users.models import *
import os
from django.db import models

from users.models import School, Country, Region, StateField, TNCounty
from teachercert.models import SchoolYear, Teacher
from datetime import date
from django.utils import timezone
from django.core.exceptions import ValidationError
from django import forms
import numpy as np

from ISEIapp.storage_backends import MediaStorage


class ReportType(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=3, default="ST")
    order_number = models.PositiveSmallIntegerField(default=0)
    for_all_schools = models.BooleanField(default=False)
    view_name = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ['order_number']

class ReportDueDate(models.Model):
    due_date = models.DateField()
    report_type = models.ForeignKey(ReportType, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    opening_report = models.BooleanField(default=False)
    class Meta:
        verbose_name_plural = "Report due dates"
    def __str__(self):
        return self.region.name +", "+ self.report_type.name

    def get_actual_due_date(self, school=None, school_year = None):
        if school:
            try:
                return SchoolSpecificReportDueDate.objects.get(
                    school=school, report_type=self.report_type,
                ).get_actual_due_date(school_year)
            except SchoolSpecificReportDueDate.DoesNotExist:
                pass  # Fallback to the region-based one

        # Fetch the active school year if no school year given
        if not school_year:
            school_year = SchoolYear.objects.get(current_school_year=True)

        # Extract the start and end years from the active school year
        start_year, end_year = map(int, school_year.name.split('-'))

        # Extract the month and day from the due_date field
        month = self.due_date.month
        day = self.due_date.day

        # Use the start year for opening reports, end year otherwise
        if self.opening_report:
            year = start_year
        elif month < 10:
            year = end_year
        else:
            year = start_year

        # Construct a new datetime object with the correct year
        return timezone.datetime(year=year, month=month, day=day).date()

class SchoolSpecificReportDueDate(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    report_type = models.ForeignKey(ReportType, on_delete=models.CASCADE)
    due_date = models.DateField()
    opening_report = models.BooleanField(default=False)

    def get_actual_due_date(self, school_year=None):
        if not school_year:
            school_year = SchoolYear.objects.get(current_school_year=True)

        start_year, end_year = map(int, school_year.name.split('-'))

        month = self.due_date.month
        if self.opening_report and month > 3:
            year = start_year
        else:
            year = end_year

        return timezone.datetime(year=year, month=month, day=self.due_date.day).date()

class AnnualReport(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    school_year = models.ForeignKey(SchoolYear, on_delete=models.CASCADE)
    report_type = models.ForeignKey(ReportType, on_delete=models.CASCADE, null=True, blank=True)
    submit_date = models.DateField(null=True, blank=True)
    last_update_date = models.DateField(null=True, blank=True)
    def __str__(self):
        return self.report_type.name + " " + self.school.abbreviation + " (" + self.school_year.name + ")"

    class Meta:
        unique_together = (('school', 'school_year', 'report_type'),)
        ordering = ('school_year', 'school', 'report_type')

    def due_date(self):
        # Try to find a school-specific due date first
        specific_due = SchoolSpecificReportDueDate.objects.filter(
            school=self.school, report_type=self.report_type).first()

        if specific_due:
            return specific_due.get_actual_due_date(school_year=self.school_year)

        # Fallback to region-level due date
        region = self.school.street_address.country.region
        region_due = ReportDueDate.objects.filter(
            report_type=self.report_type,region=region).first()

        if region_due:
            return region_due.get_actual_due_date(school=self.school, school_year=self.school_year)

        return None

    def due_date_plus(self,days=None):
        days = days or 14
        return self.due_date() + timezone.timedelta(days=days)


#personnel data collection
    def total_personnel(self):
        return self.personnel_set.exclude(status=StaffStatus.NO_LONGER_EMPLOYED).count()

    def not_returned_personnel(self):
        return self.personnel_set.filter(status=StaffStatus.NO_LONGER_EMPLOYED).count()

    def retention_rate(self):
        total = self.total_personnel()
        if total == 0:
            return None  # or 0.0 if you prefer
        not_returned = self.not_returned_personnel()
        rate = (total - not_returned) / total * 100
        return round(rate, 1)

# Employee Data
class Degree(models.Model):  # Changed to a model
    name = models.CharField(max_length=30, unique=True)
    rank = models.PositiveSmallIntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

class SubjectCategory(models.TextChoices):
    BIBLE = 'B', 'Bible'
    COMPUTER_TECH = 'C', 'Computer/Tech'
    FINE_ARTS = 'F', 'Fine Arts'
    LANGUAGE_ARTS = 'L', 'Language Arts'
    MATH = 'M', 'Math'
    MODERN_LANGUAGE = 'ML', 'Modern Language'
    SCIENCE = 'SC', 'Science'
    SOCIAL_STUDIES = 'SS', 'Social Studies'
    VOCATIONAL_ARTS_COURSES = 'V', 'Vocational Arts Courses'
    WELLNESS_HEALTH_PE = 'W', 'Wellness/Health/PE'
    ELEMENTARY = 'E', 'Elementary'
    MENTORSHIP = 'MT', 'Mentorship'

class Subject(models.Model):
    name = models.CharField(max_length=100, unique=True)
    category = models.CharField(
        max_length=50,
        choices=SubjectCategory.choices,
    )

    class Meta:
        ordering = ['category', 'name']
    def __str__(self):
        return self.name

class StaffCategory(models.TextChoices):
    ADMINISTRATIVE = 'A', 'Administrative'
    TEACHING = 'T', 'Teaching'
    GENERAL_STAFF ='G', 'General_Staff'

CATEGORY_EXPLANATION_MAP = {
    'A': '(President, Principal, Vice Principal, Business Manager, Registrar, Vocational Coordinator)',
    'T': '(Teachers, Life Skills Teachers, Deans, Librarian)',
    'G': '(Administrative Asst, Office staff, Vocational supervisors, Food Service Director, School Nurse, Other support staff)',
}

class StaffPosition(models.Model):
    name = models.CharField(max_length=100, unique=True)
    category = models.CharField(
        max_length=50,
        choices=StaffCategory.choices,
    )
    teaching_position=models.BooleanField(default=False)
    class Meta:
        ordering = ['category', 'name']
    def __str__(self):
        return self.name

class StaffStatus(models.TextChoices):
    FULL_TIME = 'FT', 'Full Time'
    PART_TIME = 'PT', 'Part Time'
    VOLUNTEER = 'VO', 'Volunteer'
    NO_LONGER_EMPLOYED = 'NE', 'No Longer Employed'
    LEAVE_OF_ABSENCE = 'LO', 'Leave of Absence'

class Personnel(models.Model):
    annual_report = models.ForeignKey(AnnualReport, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)

    status = models.CharField("status", max_length=2,
                              choices=StaffStatus.choices, default=StaffStatus.FULL_TIME, )

    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True, blank=True)

    positions = models.ManyToManyField(StaffPosition)
    degrees = models.ManyToManyField(Degree, through='PersonnelDegree', blank=True)

    subjects_teaching = models.ManyToManyField(Subject, blank=True, related_name="subjects_teaching")
    subjects_taught = models.ManyToManyField(Subject, blank=True, related_name="subjects_taught")

    years_work_experience = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Years of Work Experience")
    years_teaching_experience = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Years of Teaching Experience")
    years_administrative_experience = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name="Years of Administrative Experience")

    years_at_this_school = models.PositiveSmallIntegerField(default=1)

    email_address = models.EmailField(null=True, blank=True)
    phone_number = models.CharField(max_length=25, null=True, blank=True)

    sda=models.BooleanField(default=True, verbose_name="SDA")

    class Meta:
        unique_together = (('first_name', 'last_name', 'annual_report'),)

    def __str__(self):
        return self.first_name + " " + self.last_name


class PersonnelDegree(models.Model):  # Now has a foreign key to Degree
    personnel = models.ForeignKey(Personnel, on_delete=models.CASCADE)
    degree = models.ForeignKey(Degree, on_delete=models.CASCADE, related_name='personnel_degrees')
    area_of_study = models.CharField(max_length=100, null=False, blank=False)


GRADE_LEVEL_DICT = {
        'Pre-K': -2,
        'K': -1,
        '0': 0,
        '1': 1,
        '2': 2,
        '3': 3,
        '4': 4,
        '5': 5,
        '6': 6,
        '7': 7,
        '8': 8,
        '9': 9,
        '10': 10,
        '11': 11,
        '12': 12,
        'Graduated':13,
        'GA-I': 14,
        'GA-II': 15,
        'GA-III': 16,
    }
class Student(models.Model):

reporting/templates/employee_report.html
{% extends 'reporting_base.html' %}

{% load static %}

{% block title %} Employee Report {% endblock title %}


{% block content %}

    {% if 'employee_report_display' not in request.path %}
         <h6 style="text-align:left">Employee Report {{ school}} ({{ school_year }})</h6>

        <div class="card card-body">
            <form method="post">
                {% csrf_token %}
                <div class="row d-flex flex-wrap justify-content-center">
                    <div class="col-auto my-1">
                        <a class="btn btn-sm btn-ISEIyellow" href="{% url 'import_employee_prev_year' arID %}">
                            Import Employees from {{ school_year.get_previous_school_year }}
                        </a>
                    </div>
                    <div class="col-auto my-1">
                        <button class="btn btn-sm btn-ISEIblue2" type="submit" name="save">
                            Save and Finalize Later
                        </button>
                    </div>
                    <div class="col-auto my-1">
                        <button class="btn btn-sm btn-success" type="submit" name="complete">
                            Report Complete
                        </button>
                    </div>
                    <div class="col-auto my-1">
                        <a class="btn btn-sm btn-outline-ISEIblue4" href="{% url 'employee_report_all' arID %}">
                            Include No Longer Employed
                        </a>
                    </div>
                    <div class="col-auto my-1">
                        <a class="btn btn-sm btn-ISEIblue1" href="{% url 'employee_report_export' arID %}">
                            Export to Excel
                        </a>
                    </div>
                </div>
            </form>
        </div>
        <div class="row ml-5">
            {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
    {% else %}
        <h6 style="text-align:right">Employee Report {{ school}} ({{ school_year }})</h6>
    {% endif %}

    <div class="card card-body">

     {% for personnel_group in personnel_groups %}

         <div class="row mt-2">
            <div class="col-auto">
                <h6 class="toggle-table clickable" data-target="#table-{{ forloop.counter }}">{{ personnel_group.group_name }}</h6></div>
            <div class="col-auto">
                 {% for key, explanation in map.items %}
                    {% if key == personnel_group.code %}
                        {{ explanation }}
                    {% endif %}
                {% endfor %}
            </div>
         </div>
        <table class="table table-sm table-bordered table-striped" id="table-{{ forloop.counter }}" style="display: table;">
            <thead class="table-ISEIblue4">
                <tr>
                    {% if 'employee_report_display' not in request.path %}
                        <th rowspan="2"></th>
                    {% endif %}
                    <th rowspan="2">Name</th>
                    <th rowspan="2">Status</th>
                    <th rowspan="2">Positions</th>
                    <th rowspan="2">Degrees</th>
                    <th colspan="2" style="text-align: center">Years Experience</th>
                    <th rowspan="2">Email Address</th>
                    <th rowspan="2">Phone Number</th>
                    <th colspan="2" style="text-align: center">ISEI/NAD Certification</th>
                    <th colspan="2" style="text-align: center">Subjects</th>
                    <th rowspan ="2">SDA</th>
                </tr>
                <tr><th>Total</th>
                    <th>At {{ school }}</th>
                    <th>Type<br> Renewal Date</th>
                    <th>Endorsements</th>
                    <th>Teaching Now</th>
                    <th>All Taught</th>
                </tr>

            </thead>
            <tbody>
            {% for personnel_dict in personnel_group.group_personnel %}
                 {% with p=personnel_dict.personnel %}
                <tr>
                    {% if 'employee_report_display' not in request.path %}
                        <td>
                            <a class="clickable" href="{% url 'employee_edit' arID=arID personnelID=p.id %}">
                                Edit
                            </a>
                        </td>
                    {% endif %}
                    <td>{% if p.teacher %}
                                <a href="{% url 'teacher_dashboard' userID=p.teacher.user.id %}">
                                    {{ p.first_name }} {{ p.last_name }}</a>
                        {% else %}
                            {{ p.first_name }} {{ p.last_name }}
                            {% if personnel_group.code in 'AT' %}
                                <hr>
                                 <a class="small error clickable" href="{% url 'register_teacher_from_employee_report' personnelID=p.id %}">Create teacher account</a>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td>{{ p.get_status_display }}</td>
                    <td>{% for pos in p.positions.all %} {{ pos }} {% if not forloop.last %}<br> {% endif %}{% endfor %}</td>
                    <td>{% for deg in p.personneldegree_set.all %} {{ deg.degree }} - {{ deg.area_of_study }} {% if not forloop.last %}<br> {% endif %}{% endfor %}</td>
                    <td>{% if p.years_administrative_experience %}
                            Administrative: {{ p.years_administrative_experience|default_if_none:""  }}<br>
                        {% endif %}
                        {% if p.years_teaching_experience %}
                            Teaching: {{ p.years_teaching_experience|default_if_none:""  }}<br>
                        {% endif %}
                        {% if p.years_work_experience %}
                            Work: {{ p.years_work_experience|default_if_none:""  }}
                        {% endif %}
                    </td>
                    <td>{{ p.years_at_this_school|default_if_none:""  }}</td>
                    <td>{{ p.email_address|default_if_none:""  }}</td>
                    <td>{{ p.phone_number|default_if_none:""  }}</td>
                    <td>{% if personnel_dict.certification_type %}
                            {{ personnel_dict.certification_type }}<br>
                            {{ personnel_dict.renewal_date }}
                        {% endif %}</td>
                    <td>{% for endorsement in personnel_dict.endorsements %}
                            {{ endorsement }}<br>
                        {% endfor %}
                    </td>
                    <td>{% for subj_teach in p.subjects_teaching.all %} {{ subj_teach }} {% if not forloop.last %}<br> {% endif %}{% endfor %}</td>
                    <td>{% for subj_t in p.subjects_taught.all %} {{ subj_t }} {% if not forloop.last %}<br> {% endif %}{% endfor %}</td>
                    <td>{% if p.sda %}Yes{% else %}No{% endif %}</td>
                </tr>
                {% endwith %}
            {% endfor %}
                {% if 'employee_report_display' not in request.path %}
                    <tr>
                        <td colspan="14" style="text-align: right">
                            <a href="{% url 'employee_add' arID=arID positionCode=personnel_group.code %}">
                              <button class="btn-ISEIblue2">Add New Personnel</button>
                            </a>
                        </td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    {% endfor %}

    </div>

<script>
    $(document).ready(function(){
      $('.toggle-table').click(function(){
        var target = $(this).data('target');
        $(target).toggle();
      });
    });
</script>



{% endblock %}

reporting/templates/report_dashboard.html
{% extends 'reporting_base.html' %}

{% block title %} Not used yet {% endblock title %}


{% block content %}


{% endblock %}

reporting/templates/student_report_display.html
{% extends 'reporting_base.html' %}
{% load static %}

{% block title %} Student Report {% endblock title %}


{% block content %}

<!-- Student Report -->
    <div class="card">
        <div class="row ml-2">
            <div class="col mt-2">
                <h6>{{ annual_report }}</h6>
            </div>
            <div class="col col-auto">
                    {% if annual_report.school.street_address.state_us == "TN" %}
                        <a href="{% url 'tn_student_export' arID=annual_report.id %}">Download Data for TN_Report</a>
                    {% endif %}
            </div>
        </div>
        <div class="row ml-2">
            <div class="col col-auto mt-2">
                <form method="GET">
                    {{ filter_form.as_table }}
                    <input class="btn btn-sm btn-ISEIblue2" type="submit" value="Filter">
                    <a class="btn btn-sm btn-ISEIblue2" href="{% url 'student_report_display' annual_report.id %}" class="btn btn-default">Reset</a>
                </form>
            </div>

        </div>
<!-- table with student data -->
        <div class="scrollable-table scrollable-table2 mt-2">
                <table class="table table-striped table-bordered">
                    <thead class="table-ISEIblue4 sticky_head">
                        <tr><th>#</th>
                            <th>Name</th><th>Address</th>
                            {% if annual_report and annual_report.school and annual_report.school.street_address.country and annual_report.school.street_address.country.code == 'US' %}
                                <th>US State</th>
                                {% if annual_report.school.street_address.state_us == 'TN' %}
                                    <th>TN County</th>
                                {% endif %}
                            {% endif %}
                            <th>Country</th>
                            <th>Grade</th>
                            <th>Gender</th><th>Birth date</th><th>Age</th>
                            <th>Boarding</th><th>Baptized</th><th>SDA Parent</th><th>Status</th>
                            <th>Registration</th><th>Withdraw</th><th>Location</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in students %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ student.name }}</td>
                                <td>{{ student.address }}</td>
                                {% if annual_report and annual_report.school and annual_report.school.street_address.country and annual_report.school.street_address.country.code == 'US' %}
                                    <td>{{ student.us_state|default_if_none:"" }}</td>
                                    {% if annual_report.school.street_address.state_us == 'TN' %}
                                        <td>{{ student.TN_county|default_if_none:"" }}</td>
                                    {% endif %}
                                {% endif %}
                                <td>{{ student.country }}</td>
                                <td>{{ student.get_grade_level_display }}</td>
                                <td>{{ student.get_gender_display|default_if_none:"" }}</td>
                                <td>{{ student.birth_date|default_if_none:"" }}</td>
                                <td>{{ student.age_at_registration }}</td>

                                <td>{{ student.boarding.value|yesno:"Yes,No" }}</td>
                                <td>{{ student.get_baptized_display|default_if_none:"" }}</td>
                                <td>{{ student.get_parent_sda_display|default_if_none:"" }}</td>
                                <td>{{ student.get_status_display }}</td>

                                <td>{{ student.registration_date }}</td>
                                <td>{{ student.withdraw_date|default_if_none:"" }}</td>
                                <td>{{ student.get_location_display }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>



<!--buttons-->
            <div class="row mb-2 mt-2">
                <div class="col d-flex justify-content-center">
                    <a class="btn btn-sm btn-ISEIblue2 loading_spinner" href="{% url 'student_report' annual_report.id %}">Edit Report</a>
                </div>
                <div class="col d-flex justify-content-center">
                    <button class="btn btn-sm btn-ISEIblue2 loading_spinner" onclick="printTable()">Print Table</button>
                </div>
            </div>
    </div>

        <!-- Loading spinner -->
        <div id="loading" style="display: none;">
            <img id="loading-image" src="{% static 'appfiles/Atom.gif' %}" alt="Loading..."/>
            <p id="loading-text">Please wait, loading...</p>
        </div>


    <script>

         $(window).on('pageshow', function() {
                $('#loading').hide();
            });

        $(document).ready(function() {
            $('a.loading_spinner').click(function() {
                $('#loading').show();
            });
        });

        function printTable() {
            var printContents = document.querySelector('.scrollable-table2').outerHTML;
            var myWindow = window.open('', '', 'height=600,width=800');
            myWindow.document.write('<html><head><title>Print</title>');
            myWindow.document.write('<style>/* Your CSS for printed table here */</style>');
            myWindow.document.write('</head><body>');
            myWindow.document.write(printContents);
            myWindow.document.write('</body></html>');
            myWindow.document.close();
            myWindow.onload=function(){
                myWindow.focus();
                myWindow.print();
            }
        }



    </script>

{% endblock %}