ISEIapp/urls.py
from django.contrib import admin  #default admin site built by django
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('teachercert.urls')),
    path('', include('emailing.urls')),
    path('', include('reporting.urls')),
    path('', include('services.urls')),
    path('', include('accreditation.urls')),
    path('', include('apr.urls')),
    path('', include('selfstudy.urls')),
    path('', include('annualvisit.urls')),

    # path('paypal/', include('paypal.standard.ipn.urls')),
    # path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #static files served by the server
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #static files uploaded by the user during development

#if settings.DEBUG:
#    import debug_toolbar

#    urlpatterns += [
#       path('__debug__/', include(debug_toolbar.urls)),
#   ]

apr/urls.py
from django.urls import path
from . import views


urlpatterns = [

    #ISEI APR addition links
    path('manage_apr/<int:accreditation_id>/', views.manage_apr, name='manage_apr'),
    path('apr/<int:apr_id>/add_action_plan_directives/', views.add_action_plan_directives, name='add_action_plan_directives'),
    path('apr/<int:apr_id>/add_priority_directives/', views.add_priority_directives, name='add_priority_directives'),
    path('apr/<int:apr_id>/add_directives/', views.add_directives, name='add_directives'),
    path('apr/<int:apr_id>/add_recommendations/', views.add_recommendations, name='add_recommendations'),

    path('apr/<int:accreditation_id>/action_plan/', views.manage_action_plan, name='add_action_plan'),
    path('apr/<int:accreditation_id>/action_plan/<int:action_plan_id>/', views.manage_action_plan, name='edit_action_plan'),


    path('apr_progress_report/<int:apr_id>/', views.apr_progress_report, name='apr_progress_report'),
    path('update_progress/<int:progress_id>/', views.update_progress, name='update_progress'),
    path('update_progress_status/', views.update_progress_status, name='update_progress_status'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('update_actionplandirective_completed_date/', views.update_actionplandirective_completed_date, name='update_actionplandirective_completed_date'),

    path('apr/<int:apr_id>/update-timestamp/', views.update_apr_timestamp, name='update_apr_timestamp'),
    path('apr/<int:apr_id>/submit-timestamp/', views.submit_apr_timestamp, name='submit_apr_timestamp'),

]

teachercert/urls.py
from django.contrib import admin  #default admin site built by django
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [

    path('teacherdashboard/<str:userID>/', views.teacherdashboard, name='teacher_dashboard'),
    path('principalteachercert/<str:schoolID>/', views.principalteachercert, name='principal_teachercert'),
    path('isei_teachercert_dashboard/', views.isei_teachercert_dashboard, name='isei_teachercert_dashboard'),
    #path('iseiteachers/', views.isei_teachers, name='isei_teachers'),

    # teacher urls pk - teacher.id
    path('myCEUdashboard/<str:pk>/', views.myCEUdashboard, name='myCEUdashboard'),
    path('my_academic_classes/<str:pk>/', views.my_academic_classes, name='my_academic_classes'),

    path('update_ceuinstance/<str:pk>/', views.updateCEUinstance, name="update_ceuinstance"),
    path('delete_ceuinstance/<str:pk>/', views.deleteCEUinstance, name="delete_ceuinstance"),
    path('update_academic_class/<str:pk>/', views.update_academic_class, name="update_academic_class"),
    path('delete_academic_class/<str:pk>/', views.delete_academic_class, name="delete_academic_class"),

    path('ceu_info/', views.ceu_info, name="ceu_info"),

    # create PDA instances and reports. View submitted PDAs
    # new record: pk - user ID, sy- School-year,  #existing record: recId - record ID
    path('create_ceu/<str:recId>/', views.createCEU, name='create_ceu'),
    path('create_report/<str:pk>/<str:sy>/', views.createCEUreport, name='create_report'),
# Ajax for dependent dropdowns and info
    path('ajax/load_CEUtypes/', views.load_CEUtypes, name = 'ajax_load_CEUtypes'),
    path('ajax/load_evidence/', views.load_evidence, name = 'ajax_load_evidence'),

#if we want the add the ceuInstance separately (actually, if we do that we should just reuse update!)
#    path('add_instance/<str:reportID>/',views.add_instance, name='add_instance'),

    #pk is teacher ID
    path('teachercert_application/<str:pk>/', views.teachercert_application, name='teachercert_application'),
    path('teachercert_application_done/<str:pk>/', views.teachercert_application_done, name='teachercert_application_done'),


    # principal urls
    #path('principal_teachercert/', views.principal_teachercert, name='principal_teachercert'),
    path('principal_ceu_approval/', views.principal_ceu_approval, name='principal_ceu_approval'),
    path('principal_ceu_approval/<str:recID>/', views.principal_ceu_approval, name='principal_ceu_approval'),
    path('principal_ceu_approval/<str:recID>/<str:instID>/', views.principal_ceu_approval, name='principal_ceu_approval'),
    path('background_check/<str:schoolid>/', views.mark_background_check, name='background_check'),

    # isei staff and principal urls
    path('CEUreports/', views.CEUreports, name='CEUreports'),

    # isei staff urls
    path('isei_teachercert/', views.isei_teachercert, name='isei_teachercert'),

    path('manage_tcertificate/<str:pk>/', views.manage_tcertificate, name='manage_tcertificate'),
    path('manage_tcertificate/<str:pk>/<str:certID>/', views.manage_tcertificate, name='manage_tcertificate'),
    path('delete_tcertificate/<str:certID>/', views.delete_tcertificate, name='delete_tcertificate'),
#attempt to create and print the certificate directly
    path('create_certificate/<str:certID>/', views.create_certificate, name='create_certificate'),

    path('ajax/load_renewal/', views.load_renewal, name='ajax_load_renewal'),

    path('archive_tcertificate/<str:cID>/<str:certID>/', views.archive_tcertificate, name='archive_tcertificate'),
    path('de_archive_tcertificate/<str:cID>/<str:certID>/', views.de_archive_tcertificate, name='de_archive_tcertificate'),

    path('isei_ceu_approval/', views.isei_ceu_approval, name='isei_ceu_approval'),

    path('isei_ceu_approval/', views.isei_ceu_approval, name='isei_ceu_approval'),
    path('isei_ceu_approval/<str:repID>/', views.isei_ceu_approval, name='isei_ceu_approval'),
    path('isei_ceu_approval/<str:repID>/<str:instID>/', views.isei_ceu_approval, name='isei_ceu_approval'),
    path('isei_ceu_report_approval/<str:repID>', views.isei_ceu_report_approval,name='isei_ceu_report_approval'),
    path('isei_ceu_report_approval/<str:repID>/<str:instID>/', views.isei_ceu_report_approval, name='isei_ceu_report_approval'),

    #pdf of approved activities - unused
    #path('approved_pdf/', views.approved_pdf, name='approved_pdf'),
    #path('approved_pdf2/', views.approved_pdf2, name='approved_pdf2'),

    path('bulk_ceu_entry/', views.bulk_ceu_entry, name='bulk_ceu_entry'),
    path("bulk-edit/<int:school_year_id>/<int:school_id>/",views.bulk_ceu_edit,name="bulk_ceu_edit",),

    path('add_ISEI_CEUs/', views.add_ISEI_CEUs, name='add_ISEI_CEUs'),
    path('isei_teacher_applications/', views.isei_teacher_applications, name='isei_teacher_applications'),
    path('isei_manage_application/<str:appID>/',views.isei_manage_application, name = 'isei_manage_application'),

    path('standard_checklist/<str:teacherID>/', views.standard_checklist, name = 'standard_checklist'),

    path("school/<int:school_id>/checklist-summary/", views.school_checklist_summary, name="school_checklist_summary"),
    path("isei/checklist-summary/", views.isei_checklist_summary, name="isei_checklist_summary"),
]

teachercert/forms.py
from django.forms import ModelForm
from django import forms
from django.forms.models import inlineformset_factory, modelformset_factory

from teachercert.models import *



class CEUReportForm(ModelForm):
    class Meta:
        model = CEUReport
        fields = ('date_submitted', 'summary', 'principal_comment', 'isei_comment',)
        widgets = {
        #    'school_year': forms.TextInput(attrs={'class': 'form-controls', 'placehoder': 'Enter school year'}),
             'summary': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Enter summary for combined activities', 'rows':10}),
             'principal_comment': forms.Textarea(
                attrs={'class': 'form-controls','rows':4 }),
            'isei_comment': forms.Textarea(
                attrs={'class': 'form-controls', 'rows': 4 }),
            'date_submitted': forms.TextInput(attrs={'placeholder': 'mm/dd/yyyy', 'type':'date'}),
        }


class CEUInstanceForm(ModelForm):
    # Ajax
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ceu_type'].queryset = CEUType.objects.none()

        if 'ceu_category' in self.data:
            try:
                ceu_category_id = int(self.data.get('ceu_category'))
                self.fields['ceu_type'].queryset = CEUType.objects.filter(ceu_category_id=ceu_category_id).order_by(
                    'description')
            except (ValueError, TypeError):
                pass  # invalid input from client
        elif self.instance.pk:
            if self.instance.ceu_category:
                self.fields['ceu_type'].queryset = CEUType.objects.filter(
                    ceu_category=self.instance.ceu_category).order_by('description')
            elif self.instance.ceu_type:
                self.fields['ceu_type'].queryset = CEUType.objects.filter(pk=self.instance.ceu_type.pk)

    class Meta:
        model = CEUInstance
        fields = ('ceu_category', 'ceu_type','description', 'date_completed', 'units', 'amount', 'evidence', 'file', 'date_resubmitted')
        widgets = {
            #'ceu_category': forms.Select ('label':'CEU Category'}),
            #'ceu_type': forms.Select(attrs={'label': 'CEU Type'}),
            'file': forms.FileInput(attrs={'size': 1}),
            'date_completed': forms.TextInput (attrs = {'type':'date','placeholder':'mm/dd/yyyy', 'style':'width:130px' }),
            'amount': forms.NumberInput (attrs={'style':'width:60px' }),
            'description': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Activity Description', 'rows': 1}),
            'evidence': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Activity Description', 'rows': 1}),
        }


#not used
CEUInstanceFormSet = inlineformset_factory(CEUReport, CEUInstance, form=CEUInstanceForm, extra=1,
                                           can_delete=False)


class BulkCEUForm(forms.Form):
    school = forms.ModelChoiceField(queryset=School.objects.all(), required=False)
    school_year = forms.ModelChoiceField(queryset=SchoolYear.objects.filter(active_year=True), required=True)
    ceu_type = forms.ModelChoiceField(queryset=CEUType.objects.filter(ceu_category__name__in=["Collaboration", "Group"]), required=True)
    description = forms.CharField(
                                  required=True)
    approved_ceu = forms.DecimalField(max_digits=5, decimal_places=2, required=False)
    date_completed = forms.DateField(required=True, widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}))
    evidence = forms.CharField(required=False)
    file = forms.FileField(required=False)

    def __init__(self, *args, **kwargs):
        self.teachers = kwargs.pop('teachers', [])
        is_principal = kwargs.pop('is_principal', False)  # Pass this from the view
        super().__init__(*args, **kwargs)
        if is_principal:
            self.fields.pop('school')
        for teacher in self.teachers:
            self.fields[f'approved_ceu_{teacher.id}'] = forms.DecimalField(
                max_digits=5, decimal_places=2, required=False,
                initial= 0
            )

#not used
class RenewalForm(forms.ModelForm):
    class Meta:
        model = Renewal
        fields =('name', 'description')
        widgets ={ 'description': forms.Textarea() }

class AcademicClassForm(ModelForm):
    class Meta:
        model = AcademicClass
        fields = ('__all__')
        widgets = {
            'date_completed': forms.TextInput ( attrs = {'type':'date','placeholder':'mm/dd/yyyy', 'style':'width:130px' }),
        }

class TCertificateForm(ModelForm):
    class Meta:
        model=TCertificate
        fields =('__all__')
        widgets = {
            'issue_date': forms.TextInput( attrs={'type':'date','placeholder': 'mm/dd/yyyy'}),
            'renewal_date': forms.TextInput(attrs={'type':'date','placeholder': 'mm/dd/yyyy'}),
            'renewal_requirements': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Enter renewal requirements', 'rows': 2,}),
            'public_note': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Enter renewal requirements', 'rows': 2}),
            'office_note': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Enter renewal requirements', 'rows': 2}),
        }


class TEndorsementForm(forms.ModelForm):
    class Meta:
        model = TEndorsement
        fields = ('endorsement', 'range')
        widgets = {
            'range':forms.Textarea(attrs={'rows':1,'cols':5}),
        }


TEndorsementFormSet = inlineformset_factory(TCertificate, TEndorsement, form=TEndorsementForm,  extra = 3, can_delete=True)


class TeacherBasicRequirementForm (forms.ModelForm):
    class Meta:
        model= TeacherBasicRequirement
        fields = ('basic_requirement','met','course')

TeacherBasicRequirementFormSet = modelformset_factory(TeacherBasicRequirement, form = TeacherBasicRequirementForm, extra=0)


class TeacherCertificationApplicationForm(ModelForm):
    class Meta:
        model = TeacherCertificationApplication
        fields =('cert_level','endors_level','courses_taught',
                 'resume_file','principal_letter_file',
                 'felony','felony_description','sexual_offence','sexual_offence_description',
                 'signature', 'date')
        widgets = {
            'courses_taught': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Courses Taught','rows':1}),
            'felony_description': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Felony Description', 'rows': 10}),
            'sexual_offence_description': forms.Textarea(
                attrs = {'class': 'form-controls', 'placehoder': 'Sexual Offence Description', 'rows': 10}),
            'date': forms.TextInput(attrs={'placeholder': 'mm/dd/yyyy'}),
            'file': forms.FileInput(attrs={'size': 1}),
        }

class TeacherCertificationApplicationISEIForm(ModelForm):
    class Meta:
        model = TeacherCertificationApplication
        fields = ['public_note', 'isei_note', 'billed', 'closed', 'isei_revision_date']
        widgets = {
            'public_note': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Note visible to the teacher and principal', 'rows': 2}),
            'isei_note': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Office use only', 'rows': 2}),

            'isei_revision_date': forms.TextInput(
                attrs={'placeholder': 'mm/dd/yyyy', 'type':'date'}),
        }

class StandardChecklistForm(ModelForm):
    class Meta:
        model = StandardChecklist
        exclude=['teacher',]
        widgets = {
            'sda_education':forms.NumberInput(attrs = {'size': 3,}),
            'psychology': forms.NumberInput (attrs={'size': 3}),
            'dev_psychology': forms.NumberInput (attrs={'size': 3}),
            'assessment': forms.NumberInput(attrs={'size': 3}),
            'exceptional_child': forms.NumberInput(attrs={'size': 3}),
            'technology': forms.NumberInput(attrs={'size': 3}),
            'sec_methods': forms.NumberInput(attrs={'size': 3}),
            'sec_rw_methods': forms.NumberInput(attrs={'size': 3}),
            'credits18': forms.Textarea(attrs={'rows': 1}),
            'credits12': forms.Textarea(attrs={'rows': 1}),

            'em_science': forms.NumberInput(attrs={'size': 3}),
            'em_math': forms.NumberInput(attrs={'size': 3}),
            'em_reading': forms.NumberInput(attrs={'size': 3}),
            'em_language': forms.NumberInput(attrs={'size': 3}),
            'em_religion': forms.NumberInput(attrs={'size': 3}),
            'em_social': forms.NumberInput(attrs={'size': 3}),
            'em_health': forms.NumberInput(attrs={'size': 3}),
            'other_ed_credit': forms.NumberInput(attrs={'size': 3}),

        }

teachercert/templates/teachercert/ceu_category_dropdown_list_options.html
<!-- for Ajax ceu_types -->

<option value="">---------</option>
{% for p in ceu_types %}
<option value="{{ p.pk }}">{{ p.description }}</option>
{% endfor %}

teachercert/templates/teachercert/create_certificate2.html
<html>

<head>

    <meta charset="UTF-8">
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">

   <title> Certificate</title>
        {% load static %}

        <meta name="viewport" content="width=device-width, initial-scale=1" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">


    <style type="text/css">
       @page {  size: A4 landscape; }
        body {
            height: 842px;
            width: 595px;
            /* to centre page on screen*/
            margin-left: auto;
            margin-right: auto;
        }
  </style>

</head>

<body>
    <div class="row">
        <div class="col-sm-auto">
            Col1
        </div>
        <div class="col-sm-auto">
            Col2
        </div>
    </div>

</body>

</html>

teachercert/templates/teachercert/isei_teachercert_dashboard.html
{%  extends 'teachercert_base.html' %}

{% block title %} ISEI Staff {% endblock title %}

{% block content %}


<div class="col" align="right">
    <div class = "col-sm" >
        <br>
        <a class= "btn-sm btn-ISEIblue4" href="{% url 'register_teacher' %}"> Add new teacher</a>
        <br>
    </div>
</div>
<br>

<!-- Filter by school -->

<div class="row">
    <div class="card card-body">
        <div class="row">
            <div class="col">
                <form method="get">
                        {{ school_filter.form}}
                    <button class="btn btn-ISEIblue3 btn-sm" id="id_filter_button" type="submit">Search</button> &nbsp;
                    <a href="{%  url 'isei_teachercert_dashboard' %}">Clear all filters</a>
                </form>
            </div>
            <div class="col">
                <a href="{% url 'isei_checklist_summary' %}">
                     Missing Teacher Certification Requirements Summary
                </a>
            </div>
        </div>
    </div>
</div>

<div class = "row card card-body">
<!-- Teacher Certification Status-->
        <h5> Teacher Certification Status</h5>
          <!--  <p>Number of teachers: { { number_of_teachers }}</p>
            <p> <p>Percent of registered teachers certified:
                { % if percent_certified < 85 %}<span style="color:red">{ { percent_certified }}%</span>
                { % else %}<span style="color:green">{ { percent_certified }}%</span>{ % endif %}
            </p></p>
            -->
        <!-- Certified Teachers -->
            <p> <input type="button" class="detailbtn btn btn-sm btn-ISEIblue4" value ="Show List" id=certified>
                Certified Teachers: {{ number_of_certified_teachers }}</p>

                <table class = "table" id="details_certified" style="display:none" >
                    <thead>
                        <tr>
                            <th>School</th><th>Teacher</th><th>Certification</th><th>Endorsement</th><th>Renewal Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in valid_tcertificates %}
                          <tr>
                              <td>{{ c.teacher.user.profile.school }}</td>
                              <td><a class="nav-link" href = "{% url 'account_settings' c.teacher.user.id %}"><div class="spanyellow">Info</div></a>
                                  <a class="nav-link" href = "{% url 'teacher_dashboard' c.teacher.user.id %}">{{ c.teacher.name }}</a></td>

                              <td><a class="nav-link" href = "{% url 'manage_tcertificate' c.teacher.id c.id%}">{% if c.nad %}NAD certificate:{% endif %}{{ c.certification_type }}</a></td>
                              <td> {% for e in c.tendorsement_set.all %}
                                    {{ e }}{% if not forloop.last %},{% endif %}
                                    {% endfor %}
                              </td>
                              <td>{% if c.renewal_date > in_six_months %}
                                    {{ c.renewal_date }}
                                  {% else %}
                                    <span style="color:orange">{{ c.renewal_date }}</span>
                                  {% endif %}
                              </td>
                              <!-- td>{ % if c.teacher.academic %} Yes { % else %} No { % endif %}</td -->

                          </tr>
                        {% endfor %}
                    </tbody>
                </table>

            <p></p>
            <p> <input type="button" class="detailbtn btn btn-sm btn-ISEIblue4" value ="Show List" id=expired>
                Teachers with Expired Certificates: {{ number_of_expired_teachers}} </p>

                <table class = "table" id="details_expired" style="display:none">
                    <thead>
                        <tr>
                            <th>School</th>
                            <th>Teacher</th>
                            <th>Certification</th>
                            <th>Expiration Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in expired_tcertificates %}
                          <tr>
                                <td>{{ c.teacher.user.profile.school }}</td>
                              <td><a class="nav-link" href = "{% url 'account_settings' c.teacher.user.id %}"><div class="spanyellow">Info</div></a>
                                  <a href="{% url 'teacher_dashboard' c.teacher.user.id %}">{{c.teacher}}</a>
                              </td>
                              <td>{% if c.nad %}NAD certificate:{% endif %}<a class="nav-link" href = "{% url 'manage_tcertificate' c.teacher.id %}">{{ c.certification_type }}</a></td>
                              <td> {% if c.renewal_date < a_year_ago %}
                                     <span style="color:red"> {{ c.renewal_date }} Reinstatement Required</span>
                                {% else %}
                                    <span style="color:red">{{ c.renewal_date }} </span>
                                {% endif %}
                            </td>
                              <!-- td>{ % if c.teacher.academic %} Yes { % else %} No { % endif %}</td -->

                          </tr>
                        {% endfor %}
                    </tbody>
                </table>


            <p></p>
            <p><input type="button" class="detailbtn btn btn-sm btn-ISEIblue4" value ="Show List" id="not_certified">
                Non Certified Teachers: {{ number_of_non_certified_teachers }}
            </p>

                <table class ="table" id="details_not_certified" style="display:none">
                    <thead>
                        <tr>
                            <th>School</th><th>Teacher</th><th>Application Status</th><th</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for t in non_certified_teachers %}
                          <tr>
                              <td>{{ t.user.profile.school}}</td>
                              <td><a class="nav-link" href = "{% url 'account_settings' t.user.id %}"><div class="spanyellow">Info</div></a>
                                  <a class="nav-link" href = "{% url 'teacher_dashboard' t.user.id %}">{{t.name}}</a></td>
                              </td>
                             {% if t.teachercertificationapplication %}
                                 <td><a class="nav-link spanred" href = "{% url 'isei_manage_application' t.teachercertificationapplication.id %}">Processing</a></td>
                                {%  else %}
                              <td>Not Submitted</td>
                             {% endif %}
                              <td><a class="btn btn-sm btn-ISEIblue4" href = "{% url 'manage_tcertificate' t.id %}"><div class="span80">Add Certificate</div></a></td>
                              <!-- td>{ % if t.academic %} Yes { % else %} No { % endif %}</td> -->
                          </tr>
                        {% endfor %}
                    </tbody>
            </table>
</div>

<!-- Percent of Certified teachers/school  + background checks done-->

    <div class="card card-body" id="school_list" >
    <table class = "col-6 table table-striped" style = "table-layout: auto">
        <thead class="span80">
            <th>School</th><th>% teachers certified</th>
            <th>Teachers </th><th>Certified</th><th>Missing Background Check</th>
        </thead>
        <tbody>
            {% for s, s_info in cert_dict.items %}
                {% if s_info.teachers > 0 %}
                <tr>
                <td>
                    <div class ='btn btn-sm' onClick="selectschool({{ s.id }})">{{ s }}</div>
                </td>
                <td align = "left">
                    {% if s_info.percent < 50 %}<span style="color:red">{{ s_info.percent}}%</span>
                        {% elif s_info.percent < 70 %} <span style="color:darkorange">{{ s_info.percent}}%</span>
                        {% elif s_info.percent < 85 %} <span style="color:lightsalmon">{{ s_info.percent}}%</span>
                        {% else %} <span style="color:green">{{ s_info.percent }}%</span>
                    {% endif %}
                </td>
                <td align = "left"> {{ s_info.teachers }} </td>
                <td align = "left"> {{ s_info.certified }} </td>
                 <!--   { % for key, info in s_info.items %}
                        <td>{ { info }}</td>
                    { % endfor %} -->

                    <td align = "center">
                        {% if s_info.bc_missing > 0 %} <a href="{% url 'background_check' s.id %}" class="spanred">{{ s_info.bc_missing }}</a>
                        {% else %} <a href="{% url 'background_check' s.id %}" class="spangreen">{{ s_info.bc_missing }}</a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>


<script>

    function selectschool(id){
        $('#id_school').val(id);
        $("#id_filter_button").click();
    };

<!-- show / hide list f Certified, Expired Certification, Non-certified Teachers -->
    $('#certified').on("click", function() {
                 var value = $(this).attr('value');
                 if(value == "Show List") {
                     $("#details_certified").show();
                     $(this).attr('value',"Hide List"); }
                     if(value == "Hide List") {
                     $("#details_certified").hide();
                     $(this).attr('value',"Show List");}
    });
    $('#expired').on("click", function() {
                 var value = $(this).attr('value');
                 if(value == "Show List") {
                     $("#details_expired").show();
                     $(this).attr('value',"Hide List"); }
                     if(value == "Hide List") {
                     $("#details_expired").hide();
                     $(this).attr('value',"Show List");}
    });
    $('#not_certified').on("click", function() {
                 var value = $(this).attr('value');
                 if(value == "Show List") {
                     $("#details_not_certified").show();
                     $(this).attr('value',"Hide List"); }
                     if(value == "Hide List") {
                     $("#details_not_certified").hide();
                     $(this).attr('value',"Show List");}
    });

    document.addEventListener("DOMContentLoaded", function() {
        // Use correct form id or filter input id here
        const filterElement = document.getElementById('id_school');

        filterElement.addEventListener('change', function() {
            this.form.submit();
        });
    });


</script>



{% endblock %}