ISEIapp/urls.py
from django.contrib import admin  #default admin site built by django
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('teachercert.urls')),
    path('', include('emailing.urls')),
    path('', include('reporting.urls')),
    path('', include('services.urls')),
    path('', include('accreditation.urls')),
    path('', include('apr.urls')),
    path('', include('selfstudy.urls')),
    path('', include('annualvisit.urls')),

    # path('paypal/', include('paypal.standard.ipn.urls')),
    # path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #static files served by the server
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #static files uploaded by the user during development

#if settings.DEBUG:
#    import debug_toolbar

#    urlpatterns += [
#       path('__debug__/', include(debug_toolbar.urls)),
#   ]

apr/urls.py
from django.urls import path
from . import views


urlpatterns = [

    #ISEI APR addition links
    path('manage_apr/<int:accreditation_id>/', views.manage_apr, name='manage_apr'),
    path('apr/<int:apr_id>/add_action_plan_directives/', views.add_action_plan_directives, name='add_action_plan_directives'),
    path('apr/<int:apr_id>/add_priority_directives/', views.add_priority_directives, name='add_priority_directives'),
    path('apr/<int:apr_id>/add_directives/', views.add_directives, name='add_directives'),
    path('apr/<int:apr_id>/add_recommendations/', views.add_recommendations, name='add_recommendations'),

    path('apr/<int:accreditation_id>/action_plan/', views.manage_action_plan, name='add_action_plan'),
    path('apr/<int:accreditation_id>/action_plan/<int:action_plan_id>/', views.manage_action_plan, name='edit_action_plan'),


    path('apr_progress_report/<int:apr_id>/', views.apr_progress_report, name='apr_progress_report'),
    path('update_progress/<int:progress_id>/', views.update_progress, name='update_progress'),
    path('update_progress_status/', views.update_progress_status, name='update_progress_status'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('update_actionplandirective_completed_date/', views.update_actionplandirective_completed_date, name='update_actionplandirective_completed_date'),

    path('apr/<int:apr_id>/update-timestamp/', views.update_apr_timestamp, name='update_apr_timestamp'),
    path('apr/<int:apr_id>/submit-timestamp/', views.submit_apr_timestamp, name='submit_apr_timestamp'),

]

selfstudy/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('check-lock/<str:form_id>/', views.check_lock, name='check_lock'),
    path('acquire-lock/<str:form_id>/', views.acquire_lock, name='acquire_lock'),
    path('release-lock/<str:form_id>/', views.release_lock, name='release_lock'),

    path('setup_selfstudy/<int:accreditation_id>/', views.setup_selfstudy, name='setup_selfstudy'),
    path('selfstudy/<int:selfstudy_id>/', views.selfstudy, name='selfstudy'),

    path('<int:selfstudy_id>/selfstudy_profile/', views.selfstudy_profile, name='selfstudy_profile'),
    path('<int:selfstudy_id>/selfstudy_profile/read_only/', views.selfstudy_profile, {'readonly': True}, name='selfstudy_profile_readonly'),

    path('<int:selfstudy_id>/profile_history/', views.profile_history, name='profile_history'),
    path('<int:selfstudy_id>/profile_history/read_only/', views.profile_history, {'readonly': True}, name='profile_history_readonly'),

    path('<int:selfstudy_id>/profile_financial/', views.profile_financial, name='profile_financial'),
    path('<int:selfstudy_id>/profile_financial/read_only/', views.profile_financial, {'readonly': True}, name='profile_financial_readonly'),

    path('<int:selfstudy_id>/profile_personnel/', views.profile_personnel, name='profile_personnel'),
    path('<int:selfstudy_id>/profile_personnel/read_only/', views.profile_personnel, {'readonly': True}, name='profile_personnel_readonly'),

    path('<int:selfstudy_id>/profile_student/', views.profile_student, name='profile_student'),
    path('<int:selfstudy_id>/profile_student/read_only/', views.profile_student, {'readonly': True}, name='profile_student_readonly'),

    path('<int:selfstudy_id>/profile_student_achievement/', views.profile_student_achievement, name='profile_student_achievement'),
    path('<int:selfstudy_id>/profile_student_achievement/read_only/', views.profile_student_achievement, {'readonly': True},
         name='profile_student_achievement_readonly'),

    path('add_standardized_test_scores/<int:school_id>/<str:school_year_name>/<str:level_type>/', views.manage_standardized_test_scores, name='add_standardized_test_scores'),
    path('edit_standardized_test_scores/<int:session_id>/', views.manage_standardized_test_scores, name='edit_standardized_test_scores'),


    path('<int:selfstudy_id>/profile_secondary_curriculum/', views.profile_secondary_curriculum, name='profile_secondary_curriculum'),
    path('<int:selfstudy_id>/profile_secondary_curriculum/read_only/', views.profile_secondary_curriculum, {'readonly': True},
         name='profile_secondary_curriculum_readonly'),

    path('<int:selfstudy_id>/profile_support_services/', views.profile_support_services, name='profile_support_services'),
    path('<int:selfstudy_id>/profile_support_services/read_only/', views.profile_support_services, {'readonly': True},
         name='profile_support_services_readonly'),

    path('<int:selfstudy_id>/profile_philanthropy/', views.profile_philanthropy, name='profile_philanthropy'),
    path('<int:selfstudy_id>/profile_philanthropy/read_only/', views.profile_philanthropy, {'readonly': True}, name='profile_philanthropy_readonly'),


    path('<int:selfstudy_id>/standard/<int:standard_id>/', views.selfstudy_standard, name='selfstudy_standard'),
    path('<int:selfstudy_id>/standard/<int:standard_id>/read_only/', views.selfstudy_standard, {'readonly': True}, name='selfstudy_standard_readonly'),

    path('<int:selfstudy_id>/selfstudy_actionplan_instructions/', views.selfstudy_actionplan_instructions, name='selfstudy_actionplan_instructions'),

    path('<int:accreditation_id>/action_plan/', views.selfstudy_actionplan, name='selfstudy_actionplan_create'),

    path('<int:accreditation_id>/selfstudy_actionplan/<int:action_plan_id>/', views.selfstudy_actionplan,
         name='selfstudy_actionplan'),
    path('<int:accreditation_id>/selfstudy_actionplan/<int:action_plan_id>/read_only/', views.selfstudy_actionplan, {'readonly': True},
         name='selfstudy_actionplan_readonly'),

    path('<int:selfstudy_id>/coordinating_team/', views.selfstudy_coordinating_team, name='selfstudy_coordinating_team'),
    path('<int:selfstudy_id>/coordinating_team/read_only/', views.selfstudy_coordinating_team, {'readonly': True}, name='selfstudy_coordinating_team_readonly'),

    path('add_coordinating_team_members/<int:selfstudy_id>/<int:team_id>/', views.add_coordinating_team_members, name='add_coordinating_team_members'),

    path('selfstudy/<int:selfstudy_id>/report/', views.selfstudy_report, name='selfstudy_report'),

    #path('<int:selfstudy_id>/completion/', views.selfstudy_completion, name='completion'),  # Optional completion page
]

apr/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone

from accreditation.models import Accreditation
from users.models import School
from selfstudy.models import SelfStudy

from ISEIapp.storage_backends import MediaStorage



# Create your models here.
class APR(models.Model):
    accreditation = models.OneToOneField(Accreditation, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True, blank=True)
    updated_at = models.DateField(blank=True, null=True)
    submitted_at = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"AAPR: {self.accreditation.school}"


class APRSchoolYear(models.Model):
    name=models.CharField(max_length=10)
    apr = models.ForeignKey(APR, on_delete=models.CASCADE, related_name='aprschoolyear', null=True, blank=True)
    recommendation=models.BooleanField(default=False)

    class Meta:
        unique_together = (("name", "apr"),)
    def __str__(self):
        return self.name

class ProgressStatus(models.Model):
    status = models.CharField(max_length=20)
    def __str__(self):
        return self.status

class ActionPlanDirective(models.Model):
    number = models.IntegerField()
    apr = models.ForeignKey(APR, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    completed_date = models.DateField(null=True, blank=True)
    note=models.TextField(null=True, blank=True, verbose_name="Supplemental Note:")


    def save(self, *args, **kwargs):
        if not self.number:
            # Get the highest number for the current APR and add 1
            max_number = ActionPlanDirective.objects.filter(apr=self.apr).aggregate(models.Max('number'))['number__max']
            self.number = (max_number or 0) + 1
        super(ActionPlanDirective, self).save(*args, **kwargs)

    def __str__(self):
        return f"Action Plan Directive {self.number}"


class PriorityDirective(models.Model):
    number = models.IntegerField()
    apr = models.ForeignKey(APR, on_delete=models.CASCADE)
    progress_status = models.ForeignKey(ProgressStatus, on_delete=models.SET_NULL, null=True)
    description = models.TextField(null=True, blank=True)
    file = models.FileField(upload_to='AAPR_support_evidence/%Y', storage=MediaStorage(), null=True, blank=True)
    note=models.TextField(null=True, blank=True, verbose_name="Supplemental Note:")


    def save(self, *args, **kwargs):
        if not self.number:
            # Get the highest number for the current APR and add 1
            max_number = PriorityDirective.objects.filter(apr=self.apr).aggregate(models.Max('number'))['number__max']
            self.number = (max_number or 0) + 1
        super(PriorityDirective, self).save(*args, **kwargs)

    def __str__(self):
        return f"Priority Directive {self.number}"

class Directive(models.Model):
    number = models.IntegerField()
    apr = models.ForeignKey(APR, on_delete=models.CASCADE)
    progress_status = models.ForeignKey(ProgressStatus, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    file = models.FileField(upload_to='AAPR_support_evidence/%Y', storage=MediaStorage(), null=True, blank=True)
    note=models.TextField(null=True, blank=True, verbose_name="Supplemental Note:")


    def save(self, *args, **kwargs):
        if not self.number:
            # Get the highest number for the current APR and add 1
            max_number = Directive.objects.filter(apr=self.apr).aggregate(models.Max('number'))['number__max']
            self.number = (max_number or 0) + 1
        super(Directive, self).save(*args, **kwargs)

    def __str__(self):
        return f"Directive {self.number}"

class Recommendation(models.Model):
    number = models.IntegerField()
    apr = models.ForeignKey(APR, on_delete=models.CASCADE)
    progress_status = models.ForeignKey(ProgressStatus, on_delete=models.SET_NULL, null=True)
    description = models.TextField(null=True, blank=True)
    file = models.FileField(upload_to='AAPR_support_evidence/%Y', storage=MediaStorage(), null=True, blank=True)
    note=models.TextField(null=True, blank=True, verbose_name="Supplemental Note:")


    def save(self, *args, **kwargs):
        if not self.number:
            # Get the highest number for the current APR and add 1
            max_number = Recommendation.objects.filter(apr=self.apr).aggregate(models.Max('number'))['number__max']
            self.number = (max_number or 0) + 1
        super(Recommendation, self).save(*args, **kwargs)

    def __str__(self):
        return f"Recommendation {self.number}"

class ActionPlan(models.Model):
    number = models.IntegerField()
    #TODO delete APR once you are sure that it's not needed (Action Plan is connected to accreditation only)
    apr = models.ForeignKey(APR, on_delete=models.CASCADE, null=True, blank=True)
    accreditation = models.ForeignKey(Accreditation, on_delete=models.CASCADE, null=True, blank=True)
    standard = models.TextField()
    objective = models.TextField()
    progress_status = models.ForeignKey(ProgressStatus, on_delete=models.SET_NULL, null=True, blank=True)
    isei_reviewed = models.BooleanField(default=True)
    file = models.FileField(upload_to='AAPR_support_evidence/%Y', storage=MediaStorage, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.pk:  # Only set the number for new instances
            existing_count = ActionPlan.objects.filter(accreditation=self.accreditation).count()
            self.number = existing_count + 1
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Action Plan #{self.number}"

class ActionPlanSteps(models.Model):
    action_plan = models.ForeignKey(ActionPlan, on_delete=models.CASCADE)
    number = models.IntegerField(null=True, blank=True)
    person_responsible = models.TextField(verbose_name="Person(s) Responsible", null=True, blank=True)
    action_steps = models.TextField(verbose_name="Action Steps", null=True, blank=True)
    start_date = models.TextField(verbose_name="Estimated Start Date", null=True, blank=True)
    completion_date = models.TextField(verbose_name="Estimated Completion Date", null=True, blank=True)
    resources = models.TextField(verbose_name="Estimated Resources", null=True, blank=True)

    class Meta:
        unique_together = ['action_plan', 'number']  # enforces number to be unique for each ActionPlan
        ordering = ['action_plan', 'number']  # sorts steps by number within each ActionPlan

    def __str__(self):
        return f"Action Plan #{self.number}"

class Progress(models.Model):
    school_year = models.ForeignKey(APRSchoolYear, on_delete=models.CASCADE, related_name="progress")
    description = models.TextField(null=True, blank=True)

    # Connect Progress to Specific Entities
    priority_directive = models.ForeignKey(PriorityDirective, on_delete=models.CASCADE, null=True, blank=True,
                                           related_name="progress")
    directive = models.ForeignKey(Directive, on_delete=models.CASCADE, null=True, blank=True, related_name="progress")
    recommendation = models.ForeignKey(Recommendation, on_delete=models.CASCADE, null=True, blank=True,
                                       related_name="progress")
    action_plan = models.ForeignKey(ActionPlan, on_delete=models.CASCADE, null=True, blank=True,
                                    related_name="progress")


    def __str__(self):
        if self.priority_directive:
            return f"Progress {self.priority_directive}, {self.school_year}"
        elif self.directive:
            return f"Progress {self.directive}, {self.school_year}"
        elif self.recommendation:
            return f"Progress {self.recommendation}, {self.school_year}"
        elif self.action_plan:
            return f"Progress {self.action_plan}, {self.school_year}"
        else:
            return f"Progress {self.school_year}"

selfstudy/templates/selfstudy/includes/selfstudy_actionplan_include.html
<!--SelfStudy Action Plan Include -->


{% for plan in action_plans %}

<div id="action-plan-{{ plan.number }}"
     class="page page-break print-section">

    <h4 class="mb-3">
        Action Plan {{ plan.number }}
    </h4>

    <table class="table table-sm table-bordered mb-3">
        <tbody>
            <tr>
                <th class="col-3">Standard</th>
                <td>{{ plan.standard|linebreaksbr }}</td>
            </tr>
            <tr>
                <th>Objective</th>
                <td>{{ plan.objective|linebreaksbr }}</td>
            </tr>
            {% if plan.progress_status %}
            <tr>
                <th>Progress Status</th>
                <td>{{ plan.progress_status }}</td>
            </tr>
            {% endif %}
        </tbody>
    </table>

    {% if plan.actionplansteps_set.all %}
        <table class="table table-sm table-bordered">
            <thead>
                <tr class="blue-header">
                    <th style="width:4%">#</th>
                    <th style="width:20%">Person(s) Responsible</th>
                    <th>Action Steps</th>
                    <th style="width:12%">Start Date</th>
                    <th style="width:12%">Completion Date</th>
                    <th style="width:15%">Resources</th>
                </tr>
            </thead>
            <tbody>
                {% for step in plan.actionplansteps_set.all %}
                <tr>
                    <td>{{ step.number }}</td>
                    <td>{{ step.person_responsible|linebreaksbr }}</td>
                    <td>{{ step.action_steps|linebreaksbr }}</td>
                    <td>{{ step.start_date }}</td>
                    <td>{{ step.completion_date }}</td>
                    <td>{{ step.resources|linebreaksbr }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="text-muted">No action steps provided.</p>
    {% endif %}

     <p class="back-to-toc">
        <a href="#toc">⬆ TOC</a>
    </p>

</div>

{% endfor %}

selfstudy/templates/selfstudy/includes/selfstudy_coordinatingteam_include.html
<div class="page page-break" >

    <h5 class="mt-4">
        Coordinating Team and Standards Assessment Teams Members
    </h5>
    <hr>

        `{% if selfstudy.teams.all %}
            <table class="table table-sm table-bordered table-striped">
                <thead class="blue-header">
                    <tr>
                        <th>Team</th>
                        <th>Members</th>
                    </tr>
                </thead>
                <tbody>
                    {% for team in selfstudy.teams.all %}
                        <tr>
                            <td>{{ team.name }}</td>
                            <td>
                                {% for member in team.ss_team.all %}
                                    {{ member.user.first_name }}
                                    {{ member.user.last_name }}{% if not forloop.last %}, {% endif %}
                                {% empty %}
                                    <em>No members</em>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p><em>No teams assigned to this self-study.</em></p>
        {% endif %}`

     <p class="back-to-toc">
        <a href="#toc">⬆ TOC</a>
    </p>
</div>

selfstudy/templates/selfstudy/includes/selfstudy_cover_include.html
<!--selfstudy_cover_include.html-->
{% load static %}

<div class="page cover-page position-relative page-break">

  <!-- Screen-only submission box -->
  <div class="noprint submission-box">
    <form method="post">
      {% csrf_token %}
      {% if not selfstudy.submission_date %}
        <h6>Due date: {{ selfstudy.accreditation.selfstudy_due_date }}</h6>
        <p>Self Study is not yet submitted</p>
        {% if school_privileges %}
          <button class="btn btn-sm btn-ISEIyellow2" type="submit" name="submit_selfstudy">
            Submit SelfStudy
          </button>
        {% endif %}
      {% else %}
        <h6 class="success">
          Self Study was submitted on {{ selfstudy.submission_date }}.
        </h6>
        {% if isei_privileges %}
          <button class="btn btn-sm btn-ISEIyellow2" type="submit" name="reopen_selfstudy">
            Reopen SelfStudy
          </button>
        {% else %}
          <h6>Please contact ISEI if you would like to make changes.</h6>
        {% endif %}
      {% endif %}
    </form>
  </div>

  <!-- Vertical title -->
  <div class="vertical-title">ISEI EDUCATION ASSOCIATION</div>

  <!-- Double vertical lines -->
  <div class="vertical-lines">
    <div class="dark"></div>
    <div class="light"></div>
  </div>

  <!-- Logo -->
  <img src="{% static 'appfiles/ISEIcolored.png' %}"
       alt="ISEI Logo"
       class="cover-logo">

  <!-- Main centered content -->
  <div class="content">
    <h1 class="school-name">
      {{ selfstudy.accreditation.school.name }}
    </h1>

      <h5 class="report-title">Self-Study Report for Accreditation</h5>

    <h5 class="visit-dates">
      {{ selfstudy.accreditation.visit_date_range }}
    </h5>
  </div>

  <footer class="footer">
    P.O. Box 946 • Dayton, TN 37321, USA
  </footer>

</div>

selfstudy/templates/selfstudy/includes/selfstudy_financial_data_include.html
{% load humanize %}
{% load template_extras %}

 <div class="page page-break">

    <h5 class="mt-4">C. Financial History</h5>
    <hr>

    <h6 class="">Two-Year Financial Overview</h6>

    <table class="table table-sm table-bordered table-striped">
        <thead class="blue-header">
            <tr>
                <th>Category</th>
                <th>Two Years Ago</th>
                <th>One Year Ago</th>
                <th>Current Year</th>
            </tr>
        </thead>
        <tbody>
            {% for key in financial_two_year_keys %}
                {% with entry=two_year_lookup|get_from_dict:key.id %}
                <tr>
                    <td>{{ key.name }}</td>

                    <td>
                        {% if entry and entry.two_years_ago is not None %}
                            ${{ entry.two_years_ago|floatformat:2|intcomma }}
                        {% else %}
                            -
                        {% endif %}
                    </td>

                    <td>
                        {% if entry and entry.one_year_ago is not None %}
                            ${{ entry.one_year_ago|floatformat:2|intcomma }}
                        {% else %}
                            -
                        {% endif %}
                    </td>

                    <td>
                        {% if entry and entry.current_year is not None %}
                            ${{ entry.current_year|floatformat:2|intcomma }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                </tr>
                {% endwith %}
            {% endfor %}
        </tbody>
    </table>

    <!-- Financial Narrative / Commentary -->

        {% if school_profile and school_profile.financial_comment %}
            <h6 class="mt-4 mb-2">Financial Comment</h6>
            <p>{{ school_profile.financial_comment }}</p>
        {% endif %}

    <div class="keep-together">
        <h6 class="mt-5">Additional Financial Information</h6>
        <table class="table table-sm table-bordered table-striped">
        <thead class="blue-header">
            <tr>
                <th>Item</th>
                <th>Information</th>
            </tr>
        </thead>
        <tbody>
            {% for key in financial_additional_keys %}
                {% with entry=additional_lookup|get_from_dict:key.id %}
                <tr>
                    <td>{{ key.name }}</td>
                    <td>
                        {% if entry and entry.value %}
                            {{ entry.value }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                </tr>
                {% endwith %}
            {% endfor %}
        </tbody>
    </table>
    </div>

 <p class="back-to-toc">
        <a href="#toc">⬆ TOC</a>
    </p>
 </div>

selfstudy/templates/selfstudy/includes/selfstudy_philanthropy_include.html
 <!-- H. Philanthropy Programs -->
    <div class="print-section">
        <h5>H. Philanthropy Programs</h5>

        <p>
            <strong>
                Briefly outline the school's development program, including alumni activities and fundraising.
            </strong>
        </p>

        <p>
            {{ philanthropy_program.development_program|default:"—" }}
        </p>

          <p class="back-to-toc">
                <a href="#toc">⬆ TOC</a>
            </p>
    </div>

selfstudy/templates/selfstudy/includes/selfstudy_secondary_curriculum_include.html
<!-- selfstudy_secondary_curriculum_include.html -->

<div class="page page-break">
    <h6>F. Secondary Curriculum</h6>

    {% if secondary_curriculum.curriculum_by_category %}
        <h6 class="mt-3">1. Secondary Courses</h6>
        <p>
            The following chart lists all secondary credit courses offered to grades 9–12 students,
            including teacher assignment and instructional details.
        </p>

        {% for category, courses in secondary_curriculum.curriculum_by_category.items %}
            <h6 class="mt-3">{{ category }}</h6>

            <div class="table-responsive">
                <table class="table table-sm table-bordered table-striped text-center">
                    <thead>
                        <tr>
                            <th>Course Title</th>
                            <th>Teacher</th>
                            <th>Cert. Endorsed</th>
                            <th>Credits</th>
                            <th>Periods / Week</th>
                            <th>Minutes / Week</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for course in courses %}
                            <tr>
                                <td>{{ course.course_title }}</td>
                                <td>{{ course.teacher_name }}</td>
                                <td>
                                    {% if course.certification_endorsed %}
                                        Yes
                                    {% else %}
                                        No
                                    {% endif %}
                                </td>
                                <td>{{ course.credit_value }}</td>
                                <td>{{ course.periods_per_week }}</td>
                                <td>{{ course.minutes_per_week }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endfor %}
    {% else %}
        <p class="text-muted">No secondary curriculum data provided.</p>
    {% endif %}

    {% if secondary_curriculum.other_curriculum %}
        <hr>

        <h6 class="mt-3">2. Dual Enrollment</h6>
        <p><strong>Number of Students:</strong>
            {{ secondary_curriculum.other_curriculum.dual_enrollment_number|default:"–" }}
        </p>
        <p><strong>Location:</strong>
            {{ secondary_curriculum.other_curriculum.dual_enrollment_location|default:"–" }}
        </p>
        <p><strong>Courses Offered:</strong>
            {{ secondary_curriculum.other_curriculum.dual_enrollment_courses|default:"–" }}
        </p>

        <h6 class="mt-3">3. Vocational Education Certificates</h6>
        <p>
            {{ secondary_curriculum.other_curriculum.vocational_certificate_areas|default:"–" }}
        </p>
    {% endif %}

    <p class="back-to-toc">
        <a href="#toc">⬆ TOC</a>
    </p>
</div>

selfstudy/templates/selfstudy/includes/selfstudy_standards_include.html
<!-- selfstudy_standads_include.html -->

{% for block in standards_report.standards %}

    <div id="standard-{{ block.standard.id }}" class="page page-break">
        <h5>
            Standard {{ block.standard.number|floatformat:"0" }}:
            {{ block.standard.name }}
        </h5>

        {% if block.standard.description %}
            <p class="text-muted">
                <i>{{ block.standard.description }}</i>
            </p>
            <hr>
        {% endif %}


        {# Mission & Objectives only under that standard #}
        {% if standards_report.mission and block.standard.name == "Mission, Philosophy, Goals, & Objectives" %}
            <div class="keep-together">
                <h7>Mission Statement:</h7>{{ standards_report.mission.mission_statement|linebreaks|default_if_none:"-" }}

                <h7>Vision Statement:</h7>{{ standards_report.mission.vision_statement|linebreaks|default_if_none:"-" }}

                <h7>School Philosophy:</h7>{{ standards_report.mission.philosophy_statement|linebreaks|default_if_none:"-" }}

                <h7>School-wide Goals and Objectives:</h7>{{ standards_report.mission.school_objectives|linebreaks|default_if_none:"-" }}
            </div>
            <hr>
        {% endif %}


        {% for group in block.groups %}
            {% if group.standard != block.standard %}
                <div class="keep-together">
                    <h5>{{ group.standard.name }}</h5>
                    {% if group.standard.description %}
                        <p class="text-muted"><i>{{ group.standard.description }}</i></p>
                    {% endif %}
                </div>
            {% endif %}

            {% for row in group.indicators %}
                <div class="keep-together">
                    <p style="background-color: #EAF1F7">
                        <strong>Indicator: {{ group.standard.number|floatformat:"0"  }}.{{ forloop.counter }}</strong>
                        {{ row.indicator.description }}
                    </p>

                    {% if row.indicator.met_description %}
                        <p class="text-muted">
                            {% if "<table" in row.indicator.met_description %}
                                {{ row.indicator.met_description|safe }}
                            {% else %}
                                {{  row.indicator.met_description|linebreaksbr }}
                            {% endif %}
                        </p>
                    {% endif %}

                    {% if row.evaluation.indicator_score %}
                        <p class="score-line score-{{ row.evaluation.indicator_score.score|default:0 }}">
                            <strong>Score:</strong>
                            {{ row.evaluation.indicator_score.get_score_display|default:"–" }}
                        </p>

                            <strong>Justification:</strong>
                            <i>{{ row.evaluation.indicator_score.comment|linebreaksbr }}</i>
                            {% if row.evaluation.explanation %}
                                <p>{{ row.evaluation.explanation|linebreaksbr}}</p>
                            {% else %}
                                <p class="error">None</p>
                            {% endif %}

                        {% if row.evaluation.reference_documents %}
                            <p><strong>References: </strong>{{ row.evaluation.reference_documents|linebreaksbr }}</p>
                        {% endif %}
                    {% else %}
                        <p class="error"><em>No evaluation provided.</em></p>
                    {% endif %}
                <hr>

                </div>

            {% endfor %}
        {% endfor %}

        {% if block.narrative and block.narrative.narrative %}
            <div class="keep-together">
                <h6>Standard Narrative</h6>
                {{ block.narrative.narrative|linebreaks }}
            </div>
        {% endif %}

            <p class="back-to-toc">
                <a href="#toc">⬆ TOC</a>
            </p>
    </div>
{% endfor %}