ISEIapp/urls.py
from django.contrib import admin  #default admin site built by django
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('teachercert.urls')),
    path('', include('emailing.urls')),
    path('', include('reporting.urls')),
    path('', include('services.urls')),
    path('', include('accreditation.urls')),
    path('', include('apr.urls')),
    path('', include('selfstudy.urls')),
    path('', include('annualvisit.urls')),

    # path('paypal/', include('paypal.standard.ipn.urls')),
    # path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #static files served by the server
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #static files uploaded by the user during development

#if settings.DEBUG:
#    import debug_toolbar

#    urlpatterns += [
#       path('__debug__/', include(debug_toolbar.urls)),
#   ]

apr/urls.py
from django.urls import path
from . import views


urlpatterns = [

    #ISEI APR addition links
    path('manage_apr/<int:accreditation_id>/', views.manage_apr, name='manage_apr'),
    path('apr/<int:apr_id>/add_action_plan_directives/', views.add_action_plan_directives, name='add_action_plan_directives'),
    path('apr/<int:apr_id>/add_priority_directives/', views.add_priority_directives, name='add_priority_directives'),
    path('apr/<int:apr_id>/add_directives/', views.add_directives, name='add_directives'),
    path('apr/<int:apr_id>/add_recommendations/', views.add_recommendations, name='add_recommendations'),

    path('apr/<int:accreditation_id>/action_plan/', views.manage_action_plan, name='add_action_plan'),
    path('apr/<int:accreditation_id>/action_plan/<int:action_plan_id>/', views.manage_action_plan, name='edit_action_plan'),


    path('apr_progress_report/<int:apr_id>/', views.apr_progress_report, name='apr_progress_report'),
    path('update_progress/<int:progress_id>/', views.update_progress, name='update_progress'),
    path('update_progress_status/', views.update_progress_status, name='update_progress_status'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('update_actionplandirective_completed_date/', views.update_actionplandirective_completed_date, name='update_actionplandirective_completed_date'),

    path('apr/<int:apr_id>/update-timestamp/', views.update_apr_timestamp, name='update_apr_timestamp'),
    path('apr/<int:apr_id>/submit-timestamp/', views.submit_apr_timestamp, name='submit_apr_timestamp'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
# authentication urls + landing page url (landing is by default the login-page)
    path('', views.logoutuser, name='logout'),
    path('register_teacher/', views.register_teacher, name='register_teacher'),
    path('register_teacher_from_employee_report/<str:personnelID>/', views.register_teacher_from_employee_report, name='register_teacher_from_employee_report'),

    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutuser, name='logout'),

    path('admin/', views.loginpage, name='admin'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_form.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),

    # dashboard urls
    path('school_dashboard/<str:schoolID>/', views.school_dashboard, name='school_dashboard'),
    path('isei_dashboard/', views.isei_dashboard, name='isei_dashboard'),

    #teacher account settings
    path('account_settings/<str:userID>/', views.accountsettings, name='account_settings'),

    #path('transcript_status', views.transcript_status, name='transcript_status')
    path('update_school_info/<int:schoolID>/', views.update_school_info, name='update_school_info'),

    path('change_school_year/', views.change_school_year, name='change_school_year'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.db.models import Q
from django.apps import apps


class TNCounty(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']

class StateField(models.CharField):
    STATE_CHOICES = [
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming'),
    ]

    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 2
        kwargs['choices'] = self.STATE_CHOICES
        super().__init__(*args, **kwargs)


class Region(models.Model):
    name = models.CharField(max_length=25, unique = True)
    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=100, unique = True)
    code = models.CharField(max_length=3, unique = True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, null=True)
    ordering = ['name']
    student_occurrence = models.PositiveIntegerField(default=0)
    student_occurrence_log = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-student_occurrence_log', 'name']

#This is for the SelfStudy
class SchoolType(models.Model):
    name = models.CharField(max_length=30)
    code = models.CharField(max_length=3, unique = True, blank = True, null=True)

    class Meta:
        db_table = "users_schooltype"
    def __str__(self):
        return self.name

#This is to display to the school in the application and add SchoolType based on this
class SchoolTypeChoice(models.Model):
    code = models.CharField(max_length=5, unique=True, blank=True, null=True)
    name = models.CharField(max_length=30, unique=True, blank=True, null=True)

    def __str__(self):
        return self.name

class School(models.Model):
    name = models.CharField(max_length=50, unique=True, blank=False,
                            null=False)
    abbreviation = models.CharField(max_length=6, default=" ")
    ordering = ['name']
    foundation = models.BooleanField(default=False)

    phone_number = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=254, unique=True, blank=True, null=True)
    website = models.CharField(max_length=200, blank=True, null=True)

    street_address = models.OneToOneField('Address', related_name='school_street', on_delete=models.SET_NULL,
                                            null=True, blank=True)
    postal_address = models.OneToOneField('Address', related_name='school_postal', on_delete=models.SET_NULL,
                                           null=True, blank=True)

    principal = models.CharField(max_length=100, blank=True, null=True)
    date_hired = models.CharField(max_length=20, blank=True, null=True) #Principal Date Hired
    principal_phone = models.CharField(max_length=20, null=True, blank=True)
    principal_email = models.EmailField(max_length=254, unique=True, blank=True, null=True)

    president = models.CharField(max_length=100, blank=True, null=True)
    board_chair = models.CharField(max_length=100, blank=True, null=True)
    board_chair_phone = models.CharField(max_length=20, null=True, blank=True)
    board_chair_email = models.EmailField(max_length=254, blank=True, null=True)

    member = models.BooleanField(default=True)
    textapp= models.CharField(max_length=20, blank=True, null=True)
    fire_marshal_date = models.DateField(blank=True, null=True, verbose_name='Date of Last Fire Marshal Inspection')
    active=models.BooleanField(default=True)
    test=models.BooleanField(default=False)
    initial_accreditation_date= models.DateField(blank=True, null=True)

    worthy_student_report_needed = models.BooleanField(default=False)

    year_school_started = models.PositiveIntegerField(blank=True, null=True)

    GRADE_CHOICES = [
        ('K-8', 'K-8'),
        ('K-12', 'K-12'),
        ('9-12', '9-12'),
        ('5-12', '5-12'),
        ('GAI-III', 'GAI-III'),
    ]
    grade_levels = models.CharField(max_length=10, choices=GRADE_CHOICES, default='9-12',
                                   verbose_name="Grade Levels")

    def get_allowed_grade_choices(self):
        from reporting.models import Student
        base_choices = []

        if self.grade_levels == 'K-8':
            base_choices = [choice for choice in Student.GRADE_LEVEL_CHOICES if -2 <= choice[0] <= 8]
        elif self.grade_levels == '9-12':
            base_choices = [choice for choice in Student.GRADE_LEVEL_CHOICES if 9 <= choice[0] <= 12]
        elif self.grade_levels == '5-12':
            base_choices = [choice for choice in Student.GRADE_LEVEL_CHOICES if 5 <= choice[0] <= 12]
        elif self.grade_levels == 'K-12':
            base_choices = [choice for choice in Student.GRADE_LEVEL_CHOICES if -2 <= choice[0] <= 12]
        elif self.grade_levels == 'GAI-III':
            base_choices = [choice for choice in Student.GRADE_LEVEL_CHOICES if choice[0] in (14, 15, 16)]

        # Always include Graduated
        graduated_choice = next((c for c in Student.GRADE_LEVEL_CHOICES if c[0] == 13), None)
        if graduated_choice:
            base_choices.append(graduated_choice)

        return base_choices

    def get_grade_range(self):
        """ Returns the range of valid grade levels for the school based on the grade_levels field."""
        if self.grade_levels == 'K-8':
            return range(-2, 9)  # Pre-K to 8th grade
        elif self.grade_levels == '9-12':
            return range(9, 13)  # 9th to 12th grade
        elif self.grade_levels == '5-12':
            return range(5, 13)  # 9th to 12th grade
        elif self.grade_levels == 'K-12':
            return range(-2, 13)  # Pre-K to 12th grade
        elif self.grade_levels == 'GAI-III':
            return range(14, 17)  # GA-I to GA-III
        return range(-2, 13)  # Default if no grade_levels matched

    def get_school_type(self):
        if 'K-12' in self.grade_levels:
            return ['elementary', 'secondary']
        elif '5-12' in self.grade_levels:
            return ['elementary', 'secondary']
        elif 'K-8' in self.grade_levels:
            return ['elementary']
        elif '9-12' in self.grade_levels:
            return ['secondary']
        elif 'GAI-III' in self.grade_levels:
            return []
        return []

    #this is used for creating the self-study and selecting the indicators
    school_type=models.ManyToManyField(SchoolType, blank=True, verbose_name='School Type')
    #this is what the school will interface with
    school_type_choice = models.ManyToManyField(SchoolTypeChoice, blank=True, verbose_name='School Type (Selected by School)')

    current_school_year=models.ForeignKey('teachercert.SchoolYear', on_delete=models.CASCADE, null=True, blank=True)

    def current_accreditation(self):
        Accreditation = apps.get_model('accreditation', 'Accreditation')  # Lazy load the Accreditation model
        return Accreditation.objects.filter(school=self, status='active').first()

    def get_active_users(school):
        return User.objects.filter(profile__school=school, is_active=True).distinct()

    class Meta:
        ordering = ('name',)
    def __str__(self):
        return self.name

class AccreditationAgency(models.Model):
    name = models.CharField(max_length=100, unique=True)
    abbreviation = models.CharField(max_length=10)
    def __str__(self):
        return self.abbreviation

class OtherAgencyAccreditationInfo(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    agency = models.ForeignKey(AccreditationAgency, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    current_accreditation = models.BooleanField(default=False)
    class Meta:
        unique_together = ['school', 'agency', 'current_accreditation']
    def __str__(self):
        return self.school.name+','+self.agency.abbreviation


# User Model is automatically created by Django and we will extend it to create other models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    school = models.ForeignKey(School, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return str(self.user) + ", " + self.school.name

#Teacher Models
class Teacher(models.Model):

    joined_at = models.DateField(auto_now_add=True, blank=True)

users/templates/users/isei_dashboard.html
{% extends 'base.html' %}

{% block title %} ISEI Dashboard {% endblock title %}


{% block content %}

<div class="card">
    <div class="card-body">

        <div class="row">
            <div class="col-auto">
                <h6>Reporting</h6>
                <p><a href="{% url 'isei_reporting_dashboard' %}">ISEI Reporting Dashboard</a></p>
                <p><a href="{% url 'isei_worthy_student_scholarship' %}">Worthy Student Scholarship Reports</a></p>
                <p><a href="{% url 'download_TN_reports' schoolyearID=schoolyearID %}">Download TN reports</a></p>
                <p><a href="{% url 'download_NCPSA_directory' schoolyearID=schoolyearID %}">Download NCPSA directory</a></p>
            </div>

            <div class="col-auto">
                <h6>Directories</h6>
                <p><a href="{% url 'school_personnel_directory' %}">School + Personnel Directory</a></p>
                <p><a href="{% url 'school_directory' %}">School Directory</a></p>
                <p><a href="{% url 'personnel_directory' %}">Create New Teacher Accounts</a></p>
            </div>

            <div class="col-auto">
                <h6>Miscellaneous</h6>
                <p><a href="{% url 'isei_test_order' %}">IOWA Test Order</a></p>
            </div>

            <div class="col-auto">
                <h6>Number Crunching :) </h6>
                <p><a href="{% url 'longitudinal_enrollment' %}">Enrollment History</a></p>
                <p><a href="{% url 'staff_retention_all' %}">Staff Retention Data</a></p>

            </div>

        </div>

    </div>
</div>

{% endblock %}

users/templates/users/password_reset.html
{%  extends 'teachercert_base.html' %}

{% block title %} Reset Password {% endblock title %}

{% block content %}

<h3> Password reset </h3>

<p> Enter your email address below, and we'll email instructions for setting a new password. </p>

<form method = "POST">
	{% csrf_token %}
	{{form}}
	<input type= "submit" value = "Send Email">
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{%  extends 'teachercert_base.html' %}

{% block title %} Reset Password {% endblock title %}

{% block content %}
	<h3>Password reset complete</h3>


	<p>Your password has been set.  You may go ahead and log in now.</p>

	<p><a href="/">Log in</a></p>

	          <br class="clear">
	        </div>

{% endblock %}

users/templates/users/password_reset_form.html
{%  extends 'teachercert_base.html' %}

{% block title %} Account {% endblock title %}

{% block content %}

<h3> Enter new password </h3>

	<p> Please enter your new password twice so we can verify that you typed it in correctly.</p>

	<form method = "POST">
		{% csrf_token %}
		{{form}}
		<input type= "submit" value = "Update Password">
	</form>

{% endblock %}

users/templates/users/password_reset_sent.html
{%  extends 'teachercert_base.html' %}

{% block title %} Account {% endblock title %}

{% block content %}

	<h3> Password reset sent </h3>

	<p> We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

	<p> If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
	</p>

{% endblock %}

users/templates/users/school_dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %} School Dashboard {% endblock title %}


{% block content %}

<div class="row">
    {% if messages %}
        {% for message in messages %}
            <p class="error message {{ message.tags }}">{{ message }}</p>
        {% endfor %}
    {% endif %}
</div>

<!-- Loading spinner -->
<div id="loading" style="display: none;">
    <img id="loading-image" src="{% static 'appfiles/Atom.gif' %}" alt="Loading..."/>
    <p id="loading-text">Please wait, loading...</p>
</div>

<div class="row">
<!-- School Info -->
    <div class = "col col-auto card card-body">
        <div class="">
            <h6 class="card-title">{{ school.name }}</h6>
                <p class="card-text">
                    <strong>Address:</strong><br>
                    {{ school.street_address.address_1 }}<br>
                    {% if school.street_address.address_2 %} {{ school.street_address.address_2 }}<br>{% endif %}
                    {{ school.street_address.city }},
                    {% if school.street_address.state_us %}{{ school.street_address.state_us }},{% endif %}
                    {% if school.street_address.tn_county %}{{ school.street_address.tn_county }},{% endif %}
                    {{ school.street_address.zip_code }}<br>
                    {{ school.street_address.country }}
                </p>
                {% if school.phone_number %}
                    <p><strong>Phone:</strong> {{ school.phone_number }}</p>
                {% endif %}
                {% if school.email %}
                    <p><strong>Email:</strong> <a href="mailto:{{ school.email }}">{{ school.email }}</a></p>
                {% endif %}
                {% if school.website %}
                    <p><strong>Website:</strong> <a href="{{ school.website }}">{{ school.website }}</a></p>
                {% endif %}
                {% if school.textapp %}
                    <p><strong>Text App:</strong> {{ school.textapp}}</p>
                {% endif %}
                {% if school.principal %}
                    <p><strong>Principal:</strong> {{ school.principal }}</p>
                {% endif %}
                {% if school.president %}
                    <p><strong>President:</strong> {{ school.president }}</p>
                {% endif %}
                {% if accreditation or other_agency_accreditation_info %}
                    <strong>Accreditation</strong>
                    {% if accreditation %}
                        <p class="card-text">
                            <h7>ISEI-EA</h7>
                            <small>{{ accreditation.term_start_date }}-{{ accreditation.term_end_date }}</small>
                        </p>
                    {% endif %}
                    {% if other_agency_accreditation_info %}
                        {% for ai in other_agency_accreditation_info %}
                        <p class="card-text">
                            <span class="">{{ ai.agency.abbreviation }}:</span>
                            <span>{{ ai.start_date }}-{{ ai.end_date }}</span>
                        </p>
                        {% endfor %}
                    {% endif %}
                {% endif %}
                {% if school.grade_levels %}
                <p><strong>Grade Levels:</strong> {{ school.get_grade_levels_display }}</p>
                {% endif %}

                {% if school.street_address.state_us == "TN"  %}
                    <p>Date of last <b>Fire Marshal Inspection</b>: <br>
                        {% if is_old == None %}
                            <span class="error">Required! Please Update!!!</span>
                        {% elif is_old == True %}
                            <span class="error">{{ fire_marshal_date }} Please Update! </span>
                        {% else %}
                            <span class="success">{{ fire_marshal_date }}</span>
                        {% endif %}
                    </p>
                {% endif %}
            <a href="{% url 'update_school_info' schoolID=school.id %}" class="btn btn-sm btn-ISEIblue3">Update</a>
        </div>
    </div>
<!--Reports-->
    <div class="col col-auto card card-body">
        <h6> {{ current_school_year.name }} Reports </h6>
        <div class="container">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">Report</th>
                                <th scope="col">Due Date</th>
                                <th scope="col">Submitted On</th>
                                <th scope="col">Last Update</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for report, due_date in annual_reports %}
                                 {% if report.report_type.code == "WS" %}
                                        {% if wss == True %}
                                        <tr>
                                            <td>{{report.report_type.name}} <br>
                                                <div class="row">
                                                    <div class="col">
                                                    {% if cr_submitted %}
                                                        <a class="error report_edit" href="{% url report.report_type.view_name report.id %}"> Edit </a>
                                                    {% else %}
                                                        <span style="color: gray;">Edit</span>
                                                        <i tabindex="0" class="fas fa-info-circle span80" role="button" data-toggle="popover" data-trigger="focus" data-placement="right"
                                                                                          data-content="Closing report needs to be submitted first."></i>
                                                    {% endif %}
                                                    </div>
                                                    <div class="col">
                                                    {% if report.submit_date %}
                                                        {% with display_view=report.report_type.view_name|add:"_display" %}
                                                            <a class="" href="{% url display_view report.id %}"> View</a>
                                                        {% endwith %}</div>
                                                    {% endif %}
                                                </div>
                                            </td>
                                            <td>{{due_date}}</td>
                                            <td>{{ report.submit_date|default_if_none:"-" }}</td>
                                            <td>{{ report.last_update_date|default_if_none:"-" }}</td>
                                        </tr>
                                        {% endif %}
                                {% else %}
                                <tr>
                                    <td>{{report.report_type.name}} <br>
                                        <div class="row">
                                            <div class="col">
                                                {% if report.report_type.code == "OR" or report.report_type.code == "CR"%}
                                                    {% if report.report_type.code == "OR" %}
                                                        {% if sr_er_submitted is True %}
                                                            <a class="error report_edit" href="{% url report.report_type.view_name report.id %}"> Edit </a>
                                                        {% else %}
                                                            <span style="color: gray;">Edit</span>
                                                            <i tabindex="0" class="fas fa-info-circle span80" role="button" data-toggle="popover" data-trigger="focus" data-placement="right"
                                                                                              data-content="Student and Employee report needs to be submitted first."></i>
                                                        {% endif %}
                                                    {% endif %}
                                                    {% if report.report_type.code == "CR" %}
                                                        {% if or_submitted %}
                                                            <a class="error report_edit" href="{% url report.report_type.view_name report.id %}"> Edit </a>
                                                        {% else %}
                                                            <span style="color: gray;">Edit</span>
                                                            <i tabindex="0" class="fas fa-info-circle span80" role="button" data-toggle="popover" data-trigger="focus" data-placement="right"
                                                                                              data-content="Opening report needs to be submitted first."></i>
                                                        {% endif %}
                                                    {% endif %}

                                                {% else %}
                                                    <a class="error report_edit" href="{% url report.report_type.view_name report.id %}"> Edit </a>
                                                {% endif %}
                                            </div>
                                            <div class="col">
                                            {% with display_view=report.report_type.view_name|add:"_display" %}
                                                {% if report.submit_date %}
                                                <a class="" href="{% url display_view report.id %}"> View</a>
                                                {% endif %}
                                            {% endwith %}</div>
                                        </div>
                                    </td>

                                    <td>{{due_date}}</td>
                                    <td>{{ report.submit_date|default_if_none:"-" }}</td>
                                    <td>{{ report.last_update_date|default_if_none:"-" }}</td>
                                </tr>
                                {% endif %}
                            {% endfor %}

                            {% if apr %}
                                <tr class="table-bordered">
                                    <td><strong>AAPR</strong> <br>
                                        <a class="error report_edit" href="{% url 'apr_progress_report' apr.id %}">Edit</a>
                                    </td>
                                    <td>May 1st</td><td>{{ apr.submitted_at|default_if_none:"" }}</td>
                                    <td>{{ apr.updated_at|default_if_none:"" }}</td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
    </div>


<!-- Teacher Cert and Safety Form Link -->
    <div class = "col col-auto card">
    <!-- Safety form link-->
        <div class="card-body card">
            <h6><a href="{{ safety_form_link }}" target="_blank" rel="noopener noreferrer">Safety &amp; Maintenance Inspection Form</a></h6>
            *To be completed each school year*
        </div>

        <div class="card-body card">
<!-- Teacher Certification Status-->
            <h6 class="mb-3">
                <a href="{% url 'principal_teachercert' school.id %}">Teacher Certification </a>
            </h6>
    <!-- Percent of registered teachers -->
            <div class="mb-3">
                <p>Number of registered teachers: {{ number_of_teachers }}</p>
                <!--p>Registered academic teachers: { { number_of_academic_teachers }}</p -->
                <p> Percent of registered teachers certified:
                    {% if percent_certified < 50 %}<span style="color:red">{{ percent_certified}}%</span>
                        {% elif percent_certified < 70 %} <span style="color:orange">{{ percent_certified}}%</span>
                        {% elif percent_certified < 85 %} <span style="color:yellowgreen">{{ percent_certified}}%</span>
                        {% else %} <span style="color:green">{{ percent_certified }}%</span>
                    {% endif %}
                </p>
            </div>
        </div>

        <div class="card-body card">
            <h6> School Data</h6><hr>
            <a href="{% url 'longitudinal_enrollment_single' individual_school_name=school.name %}">Enrollment History</a>
            <hr>
            <a href="{% url 'staff_retention_school' schoolID=school.id %}">Staff Retention Data</a>
        </div>
    </div>

</div>

<script>

    $(window).on('pageshow', function() {
        $('#loading').hide();
    });

    $(document).ready(function() {
        $('a.report_edit[href*="student_report"]').click(function() {
            $('#loading').show();
        });
    });

    document.addEventListener("DOMContentLoaded", function(){
          var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-toggle="popover"]'))
          var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl, {
              trigger: 'hover'
            })
          })
        });

</script>

{% endblock %}